# Generated by Django 4.2.23 on 2025-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_change_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food_dining', 'Food & Dining'), ('transportation', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('utilities', 'Utilities'), ('education', 'Education'), ('groceries', 'Groceries'), ('fitness', 'Fitness'), ('travel', 'Travel'), ('bills_subscriptions', 'Bills & Subscriptions'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('home_garden', 'Home & Garden'), ('gifts_donations', 'Gifts & Donations'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food_dining', 'Food & Dining'), ('transportation', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('utilities', 'Utilities'), ('education', 'Education'), ('groceries', 'Groceries'), ('fitness', 'Fitness'), ('travel', 'Travel'), ('bills_subscriptions', 'Bills & Subscriptions'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('home_garden', 'Home & Garden'), ('gifts_donations', 'Gifts & Donations'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
